language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- "./gradlew cobertura coveralls --stacktrace"
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: V+98P90JRZuUrfc753trYHkMc2Dz/U/NVkK6jlIj/QVhEec7TtnIcPk4Vkysjl+XdYlpdEQ5oDIWNcXiUlVgDZhuN5dj5QwICC79yjLWu48SIKXz+O051elYG/CciNHiGrF2lIno0qwcgCOL7l6al0JHHzfsSr5jZ/3+DOmUjgeRDSgkWO2n9rGMGNHn+DoIX/4/t5fnjCIyZrBZVN14Op/BCQXekfSHfABnd3L0ZdqKPwaU1B3XUKtx5OhWjjE5dxhHd0GPwdKJdMToWfyKnI84TWX/KE7FsIrPf1FuyEzmoqQ9ed8Gwfn58OdLJfjKy4CWriQphfUxZqltrORGkt16wmCm61dKyVGCpiL1i/++LJufKc8gi66MHBy1gha1l5bB+Sv4nrPtIivKmAl6+yZ/SLscHLOUsazyKMGWmeNyU9o7tZvJyl+lcDfChEvjKYDaoonKQYqgRyrb/qxwIoiK+Wrh4r/lex5e35bJzkrveYIyfzbXxx9BrE8xcIHSgJgGykRjFyeLRaWnyGTdHkhmbHCVqRKA1Atpi3up664ZNISn0QDVsFzfnQjdHrF6oBLa4aGIKx7w7d8OkclYC5bI3v/lrC2jlD53BEHj0b3zzEX0NhPqA3hqyfTcPNngPBGDPEJYz5XycfMsWw3fEV49Kvh6TaIbu0Qp9QZi4aQ=
  - secure: lXa9XgnBJVykIPrmQCUd8gRn87vtKs/Osh8UZIshjcH58U+lhRO+QXJnrd+02elWN63zYMI240UcjBqqfoX2sFQdGEfP6jo9PjB52e2fQnE/qWkTMcQSPD5+fvlQSKmgKOa/bx4nFqIF5DwOgqIaNorbciX4M6Gb3a/Sg5G0MYqKmGouztA7uqAiOdr0w/Od6L36BCfUiStyABxIW5Dq0pTdJFykexe5MQ6iNtQRNayr0cIzTJucUZfoWYzuQk68sHESZCTbIfcoPkySyqNe5gD8ZpmpQ3tTGqRtE+y9jyAFXjjswNvb72IBssoL5o5VDV0gsxnosj7EW6jU4T3Z0k9EORUfclVkn+SYUkECuTdSU0ywMFlier/CMCF4nAppiidBowXcnPJRrZu9agjsu1l3+2phMkJR5xpHPorIE5Rh2OfkGyHeOoPWh7SCjD1e761gKrZmhf1BnNsehXifLSa41aT/jnT74tVz94IptdpuEhjhJt74janeZzzZvgHjGB+K+dWE/3EIeb3z3UPeiI6N5hl9Ty2vaowT5SQiSSmrZ1QYXsFhqrAIr1YmXPSHN+nyjwqUdz1DAKfT+NFrXRVaU2Qz9kHX2vUfn5YnIcuFXQD3X6B+GyltnViZmSsemJFwu39EnwbNGMkIYRc+IIrSVwGJUgK74OtyRXujr6k=
