language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- "./gradlew cobertura coveralls --stacktrace"
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: ahMlhaNHcEf6iFqIb3zcpG0aI3KO5hQGIY7pCgXNDwC83n0bGMofgY861VHpZv6KDTZgXSb2RCVS9apMBYw0KwFArN0vhlNNFcmvUx6yUVRvLFBnEPKIfNE1VQpjAnGHRILjzSxDmTL8LQluxuacOdoc5n14P7NlI0YadpwPYeIzZ+EgbluU5cq2TlWofN5wqCTtNrCQrB7pCYxSaD0vAaXGGyreaN2ZXwXZcO9mx8wjrEshBZLLxlUxRWlOSTRV9Jb/bOcfDjRIEv26bkB/6usYV+R+oYyf+1gOFFcHnt7Ote0RR1uZBEw5sZRC6XrRe1qohLnTerQ9S9skYaO6nOgRALkRIFrSpQ7VeYb5LJEPX8thNkFgtuHGRlkBlEIRiYSqX1UQxiuV/MEs09+RzvoSsID1WBF6CiNgjui7WOCC7RwmzhYPY7WqaxzUuxvb3ekr0ySsJW5ixACDarUCYF/ZuxdhK/vdRwC5lSALjcQ86xXOUU88BGRU2VmcZ9NutLNtuWkIYJZhmF/c36KBsFeb/3EGMXJa+vcrwrc+dRHCgiw2xtAwc3I9G4NeMPX+QgqqcBcCEqjNbrOnr7Yz9bQ2ixM2LX7WvLLCsezB27V4t4j9/Q56+AgVRoLDdbYooK4CJ3TQnLa24L3HOv4HxhGX15LwEYGIHd6QtdJaqF0=
  - secure: lZZX9YzHj4gH7yi2NqCrHfs3VeAuUgCfwi7OnFUY+BXxPS/S5tXRamYOK+kcD/96q5qh60er/I/sOnBXQ31/ij8JQbZnfDZ6S4vz86e7nqKgMkRdgk+A68kHBm9QusNK5EuvVo8YngJDiOONdoJK0Vg4nrHtLKZgdMAIa3hFcLaJzPQ3kmapOs3DDusXj1u96tdBxxBKuRUwN/EHPmAb5IJR8ayfjAfyWlKwEesvB0DnuCVvZfVAWZ9xRDvrhB0YlZBPuoGImVJpIXH7wTBqBJiMiFfT5M0i2gN0vERpKvWanCI+OTW/8iGK+9JFvvYT0pKTARQXhEosznyFbZNaAc433fouygV5lSkSOr8n4GBlHEHV0NsfzYRM2sVjn4E13451TtCw/fC5ipR8VvM2XkJkIw/a13CxbbPERLIU5U9oY7mS9aPwL2wRQfuDyPTiCvXayT1KEEzHJusxCiOipltiLt3I89w8P4R/H5mp6Q4l1VrIYSZiZ3iHbDsev5R3xDstNWaRnVkkD8O1KI1C4wOkkuSuLXXN4tEjO0/sQt+Re8QtS1lhTg0hg8I2dkQXmvqmAvRUqHCofuL+lMkFK9c3vBOLUF1liGRk9uzUKxYzuzCIZMbS94x1s5vQcOJVk2jxlUiVKbTeY3L4nMcXMsYc0lB7u6n+YWz7oJLGQWM=
